-- Adminer 4.7.1 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `questions`;
CREATE TABLE `questions` (
  `id` int(11) NOT NULL,
  `question` text NOT NULL,
  `answer_0` text NOT NULL,
  `answer_1` text NOT NULL,
  `answer_2` text NOT NULL,
  `answer_3` text NOT NULL,
  `answer_4` text NOT NULL,
  `correct_answer` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

TRUNCATE `questions`;
INSERT INTO `questions` (`id`, `question`, `answer_0`, `answer_1`, `answer_2`, `answer_3`, `answer_4`, `correct_answer`) VALUES
(0,	'Jika `x_1` dan `x_2` memenuhi persamaan `2 sin 2x – cos x = 1`, `0 <= x <= pi`, maka nilai `x_1` + `x_2` = . . .',	'`1/3 pi`',	'`2/3 pi`',	' `pi`',	'`4/3 pi`',	' `2 pi`',	3),
(1,	'Apabila `sin 18^@ = (a + sqrt(b))/c`, Maka nilai `a + b + c` adalah...',	'8',	'9',	'10',	'11',	'12',	0),
(2,	'Nilai `x` yang memenuhi pertidaksamaan `3/4 (x - 1)  <=  2x - 2` adalah . . .',	'`x <= 1`',	'`x >= 1`',	'`x <= -1`',	' `x >= -1`',	' `-1 <= x <= 1`',	0),
(3,	'Jika `S = 1! + 2! + 3! + ... + 99!` Maka angka satuan dari `S` adalah',	'9',	'8',	'5',	'3',	'0',	3),
(4,	' Pada segitiga ABC , garis yang membagi 2 sama besar sudut ABC dan garis yang membagi 2 sama besar sudut ACB berpotongan di titik O. Melalui O dibuat garis sejajar dengan BC yang memotong AB di M dan AC di N. Jika panjang AB = 12 , BC = 24 , AC = 18. Maka keliling segitiga AMN adalah ...',	'40',	'42',	'30',	'32',	'35',	2),
(5,	'Bilangan real `x` terkecil yang memenuhi sekaligus  `2^2 x >= 4` dan `| x – 1 | <= 2` adalah ...',	' `x <= -2` atau `x >= 2`',	'`x <= -1` atau `x >= 3`',	'`-1 <= x <= 3`',	'`-2 <= x <= 2`',	'`2 <= x <= 3`',	1),
(6,	' 5 ekor kambing memakan rumput seluas 5 kali ukuran lapangan bola dalam 5 hari. Maka hari yang diperlukan oleh 3 ekor kambing untuk menghabiskan rumput seluas 3 kali lapangan bola adalah ...',	'2',	'3',	'4',	'5',	'6',	3),
(7,	' Di toko buku “keluarga” Ahmad membeli 3 buku, 2 pulpen, dan 3 pensil dengan harga 47.000. Adnan membeli 2 buku, 3 pulpen, dan 1 pensil dengan harga 34.000. Diah membeli 3 buku dan 1 pensil dengan harga 39.000. jika Asmuni membeli 4 pulpen, dan 2 pensil maka ia harus membayar . . .',	'5,000',	'11,000',	'13,000',	'15,000',	'17,500',	2),
(8,	'`(sqrt(5) + 2 + sqrt(3)  + sqrt(6))(sqrt(5) - sqrt(3) + 2 - sqrt(6))(7 sqrt(2) + 2sqrt(5)) =` ...',	'`16 sqrt(10) - 44`',	'`16 sqrt(10) + 44`',	'`16 + 44 sqrt(10)`',	'`16 – 44 sqrt(10)`',	'`16 sqrt(10)`',	0),
(9,	'Akar – akar persamaan `4x – 12.2x + 32 = 0` adalah `x_1` dan `x_2` . Maka nilai `x_1 x_2` = . . .',	'3',	'6',	'8',	'12',	'32',	1),
(10,	'Bacalah teks hasil observasi berikut dengan saksama untuk menjawab soal nomor 11 sampai 13!\r\nTernyata, hewan yang bernama semut (Ant)  juga memiliki sengatan yang berbahaya. \r\nMeskipun bentuknya tidak seberapa besar, akibat yang dihasilkan sangat fatal. Semut ini bernama Captotermes Formosanus Shiraki, yaitu sejenis semut perang dan sering  juga menjadi hama tanaman. Bentuk semut ini besar, berbisa, dan dapat dijumpai di tanah pekuburan dan bukit berwarna kemerahan.\r\n Dilihat dari strukturnya, pengagalan teks laporan tersebut terdapat pada bagian ….',	'objek observasi',	'pernyataan umum',	'kalimat penjelasan',	'kalimat argumentasi',	'aspek yang dilaporkan',	1),
(11,	'Abstraksi atau ringkasan dari teks laporan hasil observasi di atas adalah …',	'Semut ada bermacam-macam jenis.',	'Semut bukan binatang abstrak dan tidak berbahaya.',	'Marilah berguru pada semut Captotermes Formosanus Shiraki.',	'Semut Captotermes Formosanus Shiraki merupakan semut perang yang sangat berbahaya.',	'Teks laporan observasi tersebut menjelaskan bagian dari semut CaptotermesFormosanus Shiraki.',	3),
(12,	'Semut ini bernama Captotermes Formosanus Shiraki, yaitu sejenis semut perang dan sering juga menjadi hama tanaman. Kalimat tersebut menunjukkan ciri kebahasaan dari teks hasil observasi yaitu adanya penggunakan ….',	'data analisis',	'sumber fakta',	' kalimat rincian',	'kalimat definisi',	'kalimat penjelasan',	2),
(13,	' Bentuk semut ini besar, berbisa, dan bisa dijumpai di tanah pekuburan dan bukit berwarna kemerahan. Kalimat ini berbentuk …. Sehingga cocok untuk menjelaskan hasil dari pengamatan.',	'bukti',	'aspek',	'bagian',	'definisi ',	'deskripsi',	0),
(14,	' Dalam struktur teks laporan hasil observasi, pernyataan umum ditulis pada bagian paragraf….',	'awal',	'akhir',	'tengah',	'tidak tentu',	'awal dan akhir',	4),
(15,	'Penulis bersikap apa adanya dalam menyampaikan hasil pengamatan, penjelasan tersebut merupakan maksud salah satu prinsip menulis laporan hasil observasi yaitu ….',	'jelas',	'objektif',	'sistematis',	'transparan',	'tepat waktu',	0),
(16,	' Di bawah ini manakah yang merupakan tujuan dari teks laporan hasil observasi …',	'Menyajikan berita atau informasi teraktual dan terpercaya.',	'Memberikan pengertian dengan gaya penulisan singkat, akurat dan padat.',	'Untuk membuat pembaca percaya dan yakin terhadap teks informasi yang dibaca.',	'Menyampaikan informasi sesuai fakta sebagai hasil dari pengamatan yang disampaikan secara sistematis.',	'Untuk melukiskan suatu objek kepada pembaca agar pembaca dapat merasakan suasana, keadaan atau pun benda yang kita ceritakan.',	3),
(17,	'Bacalah penggalan teks laporan pengamatan di bawah ini dengan saksama !\nRupanya kecepatan angin sangat memengaruhi volume suara kincir. Makin keras angin bertiup, makin cepat baling-baling kincir berputar. Gesekan sumbu kincir pun bertambah keras.\nInformasi utama yang dikemukakan dalam penggalan laporan pengamatan di atas adalah ….\n',	'jenis-jenis kecepatan angin',	'pengaruh kecepatan angin terhadap kincir angin.',	'gesekan sumbu kincir sebagai akibat dari tiupan angin',	'tiupan angin yang dapat menyebabkan berputarnya kincir angin',	'hubungan antara kecepatan angin dengan perputaran kincir angin',	1),
(18,	'Cermati sistematika penulisan teks laporan hasil observasi berikut !\r\n1. Mendaftar topik-topik yang dapat dikembangkan menjadi laporan.\r\n2. Melakukan pengamatan atau observasi lapangan dengan kriteria objek menarik yang dikuasai.\r\n3. Mengembangkan yang telah disusun menjadi suatu teks secara padu.\r\n4. Menyusun kerangka laporan dengan menomori topik-topik sesuai dengan urutan yang dikehendaki.\r\nUrutan langkah-langkah menyusun teks Laporan Hasil Observasi di atas yang tepat adalah….\r\n',	'1-2-3-4',	'2-3-4-1',	'2-1-4-3',	'3-4-2-1',	'4-3-2-1',	2),
(19,	'Suatu hari, Aziz dalam perjalanan pulang dengan mengendarai mobil. Saat itu, malam hari dan hujan turun dengan lebat. Sial bagi Aziz, lampu depan mobilnya padam. karena tidak ada penerangan yang cukup, Aziz mengikuti mobil depannya. Tiba-tiba, mobil yang diikuti Aziz mendadak berhenti, dan mengakibatkan Aziz menabrak mobil tersebut.\nAziz : “Ini bukan salah saya, salah kamu yang berhenti mendadak !” (sambil menantang)\nSopir : “Itu jelas salahmu !”\nAziz : “Kok bisa, jelas-jelas kamu yang berhenti mendadak !” (masih dengan nada menantang)\nSopir : “Kau kira ini di mana ? Di sini kan garasi rumahku\nNilai didik dari cuplikan teks anekdot di atas adalah ….\n',	'seseorang harus kritis',	'semua orang tidak boleh marah',	'kita harus berjuang sampai darah penghabisan',	'jangan lekas marah kepada orang jika belum tahu persoalan yang sebenarnya.',	'Seseorang tidak boleh emosi dalam menanggapi persolan yang sedang dihadapi.',	4),
(20,	'This text is for questions number 21-23\r\n\r\n2/11/20\r\n1206 Pino Solo Drive\r\nSanta Maia CA 93455\r\n\r\nChief Shaner\r\n4337 Snow Haven Court\r\nSanta Maria CA 93455\r\n\r\nChief Shaner:\r\nI have noticed that you are hiring potential recruitments for your fire house. I can apply my knowledge of the  outdoors and leadership skill to maintain the effectivness of your crews. This opportunity shall extended my knowledge in the fire safety field extensively.\r\nIn the Boy Scout of America I have camped and backpacked in rough conditions and know survival skills needed in bad situation. While camping, I have always used the “leave no trace” or “pack it in and pack it out policy”. I know how careless use of fire can potentially cause massive destruction to people and property.\r\nIn my Boy Scout Troop, I have leaded the construction of a trebuchet and wildlife conservation communnity service projects. In the community I lead a few graffiti removal projects that have inspired others in the community. I also have aided teens in stress management and depression. I will contct you in a week’s time regarding this letter.\r\nSincerely,\r\nJon Hoffman\r\nWhich sentence does Jon Hoffman use to convince that he is the best applicant for the position?\r\n',	' I can apply my knowledge of the  outdoors and leadrship skill to maintain the effectiviness of your crews.',	' I have leaded the construction of a trebuchet and wildlife conservation communnity service projecs.',	' know how careless use of fire can potentially cause massive destruction to people and property.',	' In the community I lead a few graffiti removal projects that have inspired others in the community.',	'While camping, I have always used the “leave no trace” or “pack it in and pack it out policy”.',	0),
(21,	'While camping, I have always used the “leave no trace” or “pack it in and pack it out policy”. What does Jon Hoffman want to express to Chief Shaner?',	'He practices a safe camp in the Boy Scout of America.',	'He persuades him to learn pack it in and pack it out policy.',	'He shares his valuable experience in joining a camp.',	' He is accustomed to working in a detail procedure.',	'He knows how to leave no trace in a wild adventure',	3),
(22,	' Based on the second paragraph, it is infered that Jon Hoffman has the values of ….',	' Independent, discipline and  social care',	'Independent, honesty and religiousness',	' Discipline, patriotism and curiousness',	' Discipline, toleration and religiousness',	'   Curiousness, patriotism and discipline',	0),
(23,	'Fadia : How did you find about the task to complete for our history class?\nTonny : I haven’t done mine yet. Is it difficult?\nFadia : Kind of. It was full of problems.\nTonny : Easy problems to solve?\nFadia : Not really. It was a review of the whole semester.\nTonny : Really?\nFadia : Sure. It was time consuming. It took about six hours\nTonny : I’m surprised at that!\nFadia : I was too. I did not expect our teacher would give us so much.\nWhat is Donny probably going to do to complete the task?',	'Note  information of history class of the semester to draw opinions.',	'Revise all  previous tasks given by the teacher during the semester',	' Find out important information from books dealing with history class',	' Search for references on history from library  to accomplish the task',	'Share ideas about complicated tasks of history class with the teacher',	0),
(24,	'Dear Sir,\nI understand that my payment is three weeks late, but that does not justify your collections office’s actions. During the past five days I have received three telephone calls and four letters. In addition, one of your representatives has contacted two of my relatives who have nothing to do with my finances. By anyone’s definition this is harassment. I expect you to stop contacting me every day and to stop calling my relatives.\nIn the meantime, please know that I plan to send you a payment within the next few days. The money will reach your office in about a week.\nSincerely yours\nAndrew Barkley\nWhat does the letter tell us about?\n',	' A complaint about the harassment done by the writer’s relatives.',	' A complaint about improper actions of payment collection',	'  A complaint about the late payment over something .',	' An apology for being late of payment.',	'A promise to do payment in about a week.',	1),
(25,	'This text is for number 26 and 27\r\n\r\nPhysics examination cannot be done on Tuesday because all the question sheets had been flooded. The school decides to delay the examination and it will be held on Monday next week. All the students who will take the exam are required to bring a ruler with a length of 30 cm.\r\nThank you for attention.\r\nThe topic of the above text is…\r\n',	' The size of a ruler',	'The wet question sheets',	' The change of exam day',	' The cancelation of the exam',	' The information to bring a ruler',	2),
(26,	'What can be inferred from the text?',	'  The principal will get a meeting',	'The question sheets are very wet',	'Some students join a competition',	'Students do not pay the school fee',	'  Students do not bring a ruler with a length of 35 cm.',	1),
(27,	'This text is for questions number 28 - 30\r\n\r\nHere is my unforgettable experience. One day I joined a story telling contest. Two of my friends and I had been chosen to take a part in the final round at the district level. I was very happy and eager to win the competition.\r\nFor preparation, I had to memorize and understand the story well.My teacher guided and taught me pronunciation, facial expression and gestures. One day, before performing, my friends and I were busy to prepare the props and costumes for the competition. Thing that me sad was my teacher rented the props and costumes for my friends but not for me. My two friends had beautiful costumes and luxurious props. Although I just wore the simple ones, I performed my best to win the competition.\r\nThe competition started. I got number 29 and my friends got number 5 and 10. I was nervous but I showed my best performance on stage. Lots of people took photos and videos of me. Finally, anxiety was gone after I had finished performing. And then, the announcement came which made three of us very uneasy. Luckily I was chosen as the first winner. I went to the stage and all the judges congratulated me and gave a plague, trophy, and money. I was very happy.\r\nWhat is the writer’s intention to write the text?',	'To tell his achievement',	' To win the competition',	'To describe his feeling to the teacher',	'To show his disappointment to teacher.',	'To tell his expectation to be the winner.',	0),
(28,	'Why did the writer feel sad before the competition?',	'She had no luxurious gown.',	' Her teacher really cares about her.',	' Her teacher was not fair to her',	' Her friends did not support her.',	'She only had a very simple dress',	2),
(29,	' From the text it can be concluded that ….',	' Practice makes performance go well',	'Being nervous helps perform well on the stage.',	'Wearing simple clothes can help win the competition.',	' It is necessary to wear beautiful costumes for the competition',	' Beautiful costumes and luxurious props are the requirements for the competition',	0),
(30,	'Fatih adalah seorang Dekan sebuah fakultas di Universitas Al-Azhar Jakarta. Ia mengetahui tindakan penyalahgunaan dana yang dilakukan oleh rekannya di Dekanat. Sebagai warga negara  yang baik dan peduli, tindakan Fatih yang tepat yaitu…',	' Membantu rekannya untuk menyadari kesalahan',	'membantu rekannya untuk memperbaiki diri dan menerima konsekuensi dari perbuatannya dengan ikhlas',	' Menyerahkan rekannya pada pihak yang berwajib ',	' Membuat rekannya faham atas tindakannya yang tidak sesuai dengan UUD 1945',	' Melaporkan rekannya ke KPK agar dihukum sesuai perbuatannya.',	1),
(31,	' Aspirasi masyarakat dibutuhkan dalam penyusunan peraturan perundang-undangan agar…',	'peraturan perundangan yang dibuat dapat diterima dan dilaksanakan dengan baik',	'masyarakat merasa aspirasinya memang dibutuhkan dan dihargai',	'Aspirasi masyarakat tetap muncul di peraturan peraturan perundang-undangan lainnya',	' Peraturan tersebut membuat masyarakat demokratis senang',	'Agar peraturan tersebut diacuhkan oleh masyarakat karena merupakan aspirasi dari masyarakat',	0),
(32,	' Perhatikan pernyataan-pernyataan di bawah ini!\n1) Menyelesaikan pertikaian secara damai.\n2) Menjamin tegaknya perubahan secara dinamis.\n3) Perlindungan Konstitusional\n4) Pengakuan terhadap keragaman\n5) Pemilihan umum yang bebas\nDari pernyataan di atas, yang merupakan nilai-nilai demokrasi adalah….\n',	'1, 2, dan 3',	'1, 2, dan 5',	'2, 3, dan 4',	'2, 4, dan 5',	' 3, 4, dan 5',	4),
(33,	'Berikut ini yang merupakan pengamalan sila pertama Pancasila adalah ...',	' Mengakui dan memperlakukan manusia sesuai dengan harkat dan martabatnya sebagai makhluk Tuhan Yang Maha Esa',	'Tidak menggunakan hak milik untuk hal-hal yang bersifat pemborosan dan gaya hidup mewah',	'Tidak memaksakan suatu agama dan kepercayaan terhadap Tuhan Yang Maha Esa kepada orang lain',	'Memajukan pergaulan demi persatuan dan kesatuan bangsa',	'Keputusan yang diambil harus dapat dipertanggungjawabkan secara moral kepada Tuhan Yang Maha Esa, menjunjung tinggi harkat dan martabat manusia, nilai-nilai kebenaran dan keadilan mengutamakan persatuan dan kesatuan demi kepentingan bersama',	2),
(34,	'Suka memberi pertolongan kepada orang lain agar dapat berdiri sendiri, merupakan nilai yang terkandung dalam Pancasila sila ...',	' Pertama',	'Kedua',	'Ketiga',	'Keempat',	'Kelima',	1),
(35,	'Tanggal lahirnya SMA NEGERI 3 SURAKARTA adalah',	'13 Agustus 1943',	'1 Agustus 1958',	' 1 Agustus 1943',	' 24 November 1958',	'13 Agustus 1958',	1),
(36,	' Arti Widya Karma Jaya adalah . . .',	'Akhlak mulia dan berbudi pekerti luhur',	'Akhlak mulia, jujur, dan berbudi pekerti luhur',	'Jujur, disiplin, dan berbudi pekerti luhur',	'Akhlak mulia, berintegritas, dan disiplin',	'Berbudi pekerti luhur, disiplin, dan berintegritas',	0),
(37,	' Alamat kampus Smaga Warung Miri adalah . . .',	' Jalan RE Martadinta No. 140',	'Jalan Prof. Yohanes No. 58',	'Jalan RE Martadinata No. 143',	'Jalan WR. Supratman No. 68',	'Jalan Prof. Yohanes No. 50',	2),
(38,	'  Lokasi tempat Gedung Smaga Kampus Kerkof adalah . . .',	' Kelurahan Jagalan, Kecamatan Banjarsari',	'Kelurahan Gandekan, Kecamatan Jebres',	'Kelurahan Purwodiningratan, Kecamatan Banjarsari',	'Kelurahan Jagalan, Kecamatan Jebres',	' Kelurahan Purwodiningratan, Kecamatan Jebres',	4),
(39,	'Urutan kepala sekolah definitif di Smaga mulai tahun 2005-2015 yaitu . . .',	' Drs. Sunarso, Drs.Sabar N., Drs. Makmur Sugeng',	' Drs. Yusmar, Drs. Makmur Sugeng, Drs. Ngadiyo',	'Drs. Sunarso, Drs. Ngadiyo, Drs. Makmur Sugeng',	'Drs. Ngadiyo, Drs. Sunarso, Drs. Makmur Sugeng',	'Drs. Ngadiyo, Drs. Sabar N., Drs. Makmur Sugeng',	2),
(40,	'MOBIL: GARASI =',	'Kandang : Kebun Binatang',	'Planet : Matahari',	'Bintang : Bumi',	'Gajah : Hutan',	'',	3),
(41,	'KAYU: GERGAJI =',	'Papan : Paku',	'Ikan : Jaring',	'Televisi : Obeng',	'Becak : Bengkel',	'',	1),
(42,	'BERPIKIR: OTAK =',	'Tertidur : Bosan',	'Berlayar : Kapal pesiar',	'Sepatu : Berlari',	'Helikopter : Baling‐baling',	'',	1),
(43,	'Manakah dari yang berikut ini tidak mempunyai kesamaan dengan yang lainnya',	'Ketipung',	'Seruling',	'Gendang',	' Rebana',	'',	1),
(44,	'WARTA =',	'Koran',	'Berita',	'Majalah',	'Artikel',	'',	1),
(45,	'STABIL ><',	'labil  ',	'Rusuh',	'Runtuh',	'Hancur',	'',	0),
(46,	'MAKAR ><',	'Muslihat',	'Jujur',	'Menutupi',	'Boleh',	'',	0),
(47,	'KEMAMPUAN PENALARAN\n Ira lebih tinggi dari Syamsul. Ali lebih tinggidaripada Heri. Heri lebih pendek daripada Gani.Syamsul dan Gani sama tingginya. Jika data di atasbenar maka manakah kondisi berikut ini yangbenar?\n',	'Ali lebih tinggi dari Gani',	'Ali lebih tinggi dari Ira',	'Syamsul lebih pendek dari Ali',	'Ira lebih tinggi dari Heri',	'',	3),
(48,	'Mulai bulan Desember tahun ini, semua pegawai harus memakai seragam perusahaan pada jamkerja. Dari pernyataan manakah kesimpulan diatas dapat ditarik?',	'Sebelum bulan Desember tahun ini, tidak adapegawai yang harus mengenakan seragamperusahaan, tetapi setelah bulan Desembersemua pegawai harus mengenakan seragamperusahaan.',	'Para pegawai perusahaan harus mengenakanseragam perusahaan sebelum bulan Desembertahun ini.',	'Beberapa pegawai mungkin telah mengenakan seragam perusahaan sebelum bulan Desember tahun ini, tetapi semua pegawai mulai diwajibkan untuk mengenakan seragam perusahaan dalam tahun bulan Desember tahun ini.',	'Pegawai adalah yang pertama yang diwajibkanmengenakan seragam perusahaan.',	'',	2),
(49,	'Yoga terlambat makan siang. Karena itu, perutnyasakit. Ia menyadari bahwa ia tidak akan kuatmelanjutkan pendakian Gunung Merapi. Di tengahjalan ia ambruk karena kecapekan. Selain itu,ternyata penyakit asma yang dideritanya kambuh.Yoga dibawa ke rumah sakit, dan ia dijenguksaudara‐saudaranya yang ingin tahu mengapa Yogatidak sanggup melanjut‐kan pendakian. Kesimpulanapakah yang dapat diambil dari cerita di atas?',	'Karena Yoga terlambat makan siang, makapenyakit asmanya kambuh.',	'Saudarasaudara Yoga menjenguknya di rumahsakit, karena ingin tahu mengapa Yoga tidaksanggup melanjutkan pendakian gunung.',	'Yoga masuk rumah sakit karena terlambatmakan siang.',	'Penyakit asma Yoga kambuh, karena ia lupamembawa perbekalan untuk makan siang.',	'',	1);

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `username` char(100) NOT NULL,
  `password` char(100) NOT NULL,
  `full_name` char(255) NOT NULL,
  `answers` text NOT NULL,
  `done` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 2019-08-23 04:50:44
